// <auto-generated />
using System;
using Infrastructrure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructrure.Migrations
{
    [DbContext(typeof(ServiceContext))]
    [Migration("20250627000328_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.OptionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OptionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SlideHistoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SlideHistoryId");

                    b.ToTable("OptionHistories");
                });

            modelBuilder.Entity("Domain.Entities.SessionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OriginalSlideId")
                        .HasColumnType("int");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SlideHistoryId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("TimeElapsed")
                        .HasColumnType("time");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserAnswer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserCreate")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserHistoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SlideHistoryId");

                    b.HasIndex("UserHistoryId");

                    b.ToTable("SessionHistories");
                });

            modelBuilder.Entity("Domain.Entities.SlideHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerCorrect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ask")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalSlideId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SlideHistories");
                });

            modelBuilder.Entity("Domain.Entities.UserHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserHistories");
                });

            modelBuilder.Entity("Domain.Entities.OptionHistory", b =>
                {
                    b.HasOne("Domain.Entities.SlideHistory", "SlideHistory")
                        .WithMany("Options")
                        .HasForeignKey("SlideHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SlideHistory");
                });

            modelBuilder.Entity("Domain.Entities.SessionHistory", b =>
                {
                    b.HasOne("Domain.Entities.SlideHistory", "SlideHistory")
                        .WithMany("SessionHistories")
                        .HasForeignKey("SlideHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.UserHistory", "UserHistory")
                        .WithMany("SessionHistories")
                        .HasForeignKey("UserHistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SlideHistory");

                    b.Navigation("UserHistory");
                });

            modelBuilder.Entity("Domain.Entities.SlideHistory", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("SessionHistories");
                });

            modelBuilder.Entity("Domain.Entities.UserHistory", b =>
                {
                    b.Navigation("SessionHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
